import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ThemeProvider,createTheme,CssBaseline,Button,TextField,Typography,Box,Chip,Alert,LinearProgress,Tabs,Tab,MenuItem,Select,Snackbar} from '@mui/material';
import {AgGridReact} from 'ag-grid-react';
import {AllCommunityModule,ModuleRegistry,themeQuartz,type ColDef,type GridApi} from 'ag-grid-community';
import type {Row} from '../electron/types';
import {useViewer} from './store';
import './style.css';
ModuleRegistry.registerModules([AllCommunityModule]);
const theme=createTheme({palette:{primary:{main:'#16744b'},background:{default:'#f7f9fb'}},typography:{fontFamily:'Segoe UI, sans-serif',button:{textTransform:'none'}},shape:{borderRadius:8}});
function letter(n:number):string{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
function App(){
 const s=useViewer(); const grid=useRef<GridApi<Row>|null>(null);const searchRef=useRef<HTMLInputElement>(null);const [toast,setToast]=useState('');const [drag,setDrag]=useState(false);const [query,setQuery]=useState('');
 useEffect(()=>{void s.refresh();return window.viewer.onOpen(()=>void useViewer.getState().open());},[]);
 useEffect(()=>{const timer=setTimeout(()=>s.set({search:query}),180);return()=>clearTimeout(timer);},[query]);
 useEffect(()=>{setQuery('');},[s.sheet?.name,s.book?.name]);
 const copy=async(text:string)=>{const result=await window.viewer.copy(text);if(result.ok)setToast('Copied to clipboard');else s.set({error:result.error});};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{const input=e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement;if(e.ctrlKey&&e.key.toLowerCase()==='f'){e.preventDefault();searchRef.current?.focus();}if(e.ctrlKey&&e.key.toLowerCase()==='c'&&!input&&s.selected){e.preventDefault();void copy(s.selected.text);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[s.selected]);
 const columns=useMemo<ColDef<Row>[]>(()=>[{headerName:'#',colId:'row',valueGetter:p=>p.data?.id,pinned:'left',width:70,sortable:false,filter:false,resizable:true},...Array.from({length:s.sheet?.columns??0},(_,c)=>({headerName:letter(c),colId:String(c),valueGetter:(p:any)=>p.data?.cells[String(c)]?.v??null,valueFormatter:(p:any)=>p.data?.cells[String(c)]?.text??'',getQuickFilterText:(p:any)=>p.data?.cells[String(c)]?.text??'',width:140,filter:'agTextColumnFilter',filterValueGetter:(p:any)=>p.data?.cells[String(c)]?.text??'',sortable:true,resizable:true,comparator:(a:any,b:any)=>a==null?(b==null?0:-1):b==null?1:typeof a==='number'&&typeof b==='number'?a-b:String(a).localeCompare(String(b),undefined,{numeric:true})}))],[s.sheet?.columns]);
 const gridTheme=useMemo(()=>themeQuartz.withParams({accentColor:'#16744b',fontFamily:'Segoe UI',fontSize:13*s.zoom/100,rowHeight:30*s.zoom/100,headerHeight:34*s.zoom/100}),[s.zoom]);
 const copyRows=()=>{const rows=grid.current?.getSelectedNodes().sort((a,b)=>(a.rowIndex??0)-(b.rowIndex??0))??[];if(!rows.length){setToast('Select rows using the checkboxes first');return;}const text=rows.map(n=>Array.from({length:s.sheet?.columns??0},(_,i)=>{const text=n.data?.cells[String(i)]?.text??'';return /[\t\r\n"]/.test(text)?'"'+text.replaceAll('"','""')+'"':text;}).join('\t')).join('\r\n');void copy(text);};
 return <Box className="app" onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDrag(false);}} onDrop={e=>{e.preventDefault();setDrag(false);if(e.dataTransfer.files[0])void s.open(undefined,e.dataTransfer.files[0]);}}>
  <header><Box><Typography variant="h6" fontWeight={700}>▦ Clear Sheet</Typography><Typography variant="caption" color="text.secondary">A simple, read-only spreadsheet viewer</Typography></Box><Chip size="small" label="READ ONLY" variant="outlined"/><Box flex={1}/><Button variant="contained" disabled={s.busy} onClick={()=>void s.open()}>Open file</Button></header>
  {s.error&&<Alert severity="error" onClose={()=>s.set({error:''})}>{s.error}</Alert>}
  {s.busy&&<LinearProgress/>}
  {s.book?<><section className="toolbar"><Typography fontWeight={600} noWrap sx={{maxWidth:300}} title={s.book.name}>{s.book.name}</Typography><TextField inputRef={searchRef} size="small" placeholder="Search sheet · Ctrl+F" value={query} onChange={e=>setQuery(e.target.value)} slotProps={{htmlInput:{'aria-label':'Search sheet'}}}/><Button disabled={!s.selected||s.busy} onClick={()=>void copy(s.selected?.text??'')}>Copy cell</Button><Button disabled={s.busy} onClick={copyRows}>Copy rows</Button><Button onClick={()=>{grid.current?.setFilterModel(null);grid.current?.applyColumnState({defaultState:{sort:null}});setQuery('');}}>Reset filters</Button><Box flex={1}/><Select size="small" value={s.zoom} inputProps={{'aria-label':'Zoom'}} onChange={e=>s.set({zoom:Number(e.target.value)})}>{[75,90,100,110,125,150,175,200].map(n=><MenuItem key={n} value={n}>{n}%</MenuItem>)}</Select></section>
   <section className="formula"><span className="address">{s.selected?.address??'—'}</span><span className="fx">fx</span><input aria-label="Formula bar" readOnly value={s.selected?.formula?'='+s.selected.formula:s.selected?.text??''} placeholder="Select a cell to view its value or stored formula"/></section>
   {s.sheet?.truncated&&<Alert severity="warning">Preview limited to {s.sheet.rows.length.toLocaleString()} rows and {s.sheet.columns} columns (up to 1 million cell positions). This sheet has {s.sheet.totalRows.toLocaleString()} rows. Search, sort and filters cover this preview only.</Alert>}
   <main className="grid" aria-busy={s.busy}>{s.sheet&&<AgGridReact<Row> key={s.book.name+s.sheet.name} theme={gridTheme} rowData={s.sheet.rows} columnDefs={columns} defaultColDef={{editable:false}} getRowId={p=>String(p.data.id)} quickFilterText={s.search} rowSelection={{mode:'multiRow',enableClickSelection:false,selectAll:'filtered'}} onGridReady={e=>{grid.current=e.api;}} onCellFocused={e=>{if(e.rowIndex==null||!e.column)return;const c=e.column.getColId();const row=e.api.getDisplayedRowAtIndex(e.rowIndex)?.data;if(!row||!/^\d+$/.test(c))return;const cell=row.cells[c];s.set({selected:{address:letter(Number(c))+row.id,text:cell?.text??'',formula:cell?.formula}});}} overlayNoRowsTemplate="No matching rows"/>}{s.busy&&<div className="loading">Reading spreadsheet…</div>}</main>
   <Tabs value={s.sheet?.name??false} onChange={(_,name)=>void s.load(name)} variant="scrollable" scrollButtons="auto">{s.book.sheets.map(name=><Tab key={name} label={name} value={name} disabled={s.busy}/>)}</Tabs>
   <footer><span>{s.sheet?`${s.sheet.rows.length.toLocaleString()} rows · ${s.sheet.columns} columns`:'Choose a sheet'}</span><span>Stored values · Macros never run · Ctrl+C copies focused cell</span></footer>
  </>:<main className="welcome"><div className="file-icon">▦</div><Typography variant="h4" fontWeight={650}>Your spreadsheets, simply viewed.</Typography><Typography color="text.secondary">Drop a file here or open one from your computer.</Typography><Typography variant="caption" color="text.secondary">XLSX · XLS · XLSM · XLSB · CSV</Typography><Button variant="contained" size="large" disabled={s.busy} onClick={()=>void s.open()}>Browse files</Button><section className="recent"><Box display="flex" justifyContent="space-between" alignItems="center"><Typography fontWeight={600}>Recent files</Typography><Button size="small" onClick={async()=>{const r=await window.viewer.clearRecent();if(r.ok)void s.refresh();else s.set({error:r.error});}}>Clear history</Button></Box>{s.recents.length?s.recents.map(path=><Button className="recent-file" key={path} disabled={s.busy} onClick={()=>void s.open(path)} title={path}>{path}</Button>):<Typography color="text.secondary" variant="body2">Opened files will appear here.</Typography>}</section></main>}
  {drag&&<div className="drop-overlay">Drop spreadsheet to open</div>}
  <Snackbar open={!!toast} autoHideDuration={2200} onClose={()=>setToast('')} message={toast}/>
 </Box>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><ThemeProvider theme={theme}><CssBaseline/><App/></ThemeProvider></React.StrictMode>);
